# Generated by Django 5.1.6 on 2025-03-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritoitem',
            options={'ordering': ['-fecha_agregado'], 'verbose_name': 'Item del Carrito', 'verbose_name_plural': 'Items del Carrito'},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto del Catálogo', 'verbose_name_plural': 'Productos del Catálogo'},
        ),
    ]
