# Generated by Django 5.1.6 on 2025-03-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_carritoitem_options_alter_catalogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritoitem',
            options={},
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
