# Generated by Django 5.1.6 on 2025-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_carritoitem_options_alter_ordenitem_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
