# Generated by Django 5.1.6 on 2025-03-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_catalogo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
