# Generated by Django 5.1.6 on 2025-03-12 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_catalogo_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordenitem',
            options={'verbose_name': 'Item de Orden', 'verbose_name_plural': 'Items de Órdenes'},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='sesion_id',
        ),
        migrations.AddField(
            model_name='orden',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
